#######################################################################################
# Project & Book settings
project: "TAVIE"
title: TAVIE
author: "Somjit Roy and Pritam Dey"
email: ''
logo: "favicon.png"                      # A path to the book logo
exclude_patterns: ["README.md"]          # Patterns to skip when building the book

# Footer copyright
copyright: "2025"

#######################################################################################
# Execution settings
execute:
  execute_notebooks: 'off'               # Whether to execute notebooks at build time
  timeout: 600                           # Max seconds per cell

#######################################################################################
# HTML-specific settings
html:
  favicon: "favicon_1.png"                  # Path to a favicon image
  navbar_number_sections: true            # Add section numbers in the navbar
  home_page_in_navbar: false              # Don’t include README.md as a page
  baseurl: "/TAVIE_JupyterBook/"          # Relative path for GitHub Pages

  analytics:                              # Updated analytics location
    google_analytics_id: "UA-148221575-1"

  use_repository_button: true             # Show “View on GitHub” button
  use_edit_page_button: false             # Hide “Edit this page” link
  use_issues_button: false                # Hide “Report issue” button

#######################################################################################
# Launch button settings
launch_buttons:
  jupyterhub_url: ""                      # Leave empty or set your JupyterHub URL
  binderhub_url: "https://mybinder.org"   # URL for Binder
  notebook_interface: jupyterlab

#######################################################################################
# Repository info
repository:
  url: "https://github.com/Roy-SR-007/TAVIE_JupyterBook"  # Repo URL
  branch: main                                          # Branch for “Edit on GitHub” links

#######################################################################################
# Sphinx config
sphinx:
  config:
    html_extra_path: ['assets']
